[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[template.environment]
  REACT_APP_API_KEY = "apiKey"
  REACT_APP_AUTH_DOMAIN = "authDomain"
  REACT_APP_DATABASE_URL = "databaseURL"
  REACT_APP_PROJECT_ID = "projectId"
  REACT_APP_STORAGE_BUCKET = "storageBucket"
  REACT_APP_MESSAGING_SENDER_ID = "messagingSenderId"
  REACT_APP_APP_ID = "appId"
  REACT_APP_NOTIFICATION_TOKEN = "notificationToken"
[functions]
  node_bundler = "esbuild"